#!/usr/bin/bash
#
# Source code checks.
#
# Run in top level
# Requires
# - pylint
# - pycodestyle
# - mypy

mod_dir="src/pyconcurrent"
export PYTHONPATH=$(/usr/bin/realpath ./src)

echo " module"
/usr/bin/pylint "$mod_dir"/*.py 
/usr/bin/pycodestyle --max-line-length=110 $mod_dir/*.py
/usr/bin/mypy --check-untyped-defs --follow-untyped-imports $mod_dir

echo " tests"
tdir="src/tests"
/usr/bin/pylint "$tdir"/*.py
/usr/bin/pycodestyle "$tdir"/*.py
/usr/bin/mypy --check-untyped-defs --follow-untyped-imports "$tdir"


