#!/bin/bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: © 2025-present  Gene C <arch@sapience.com>
#
# installer script for python-parallel
# e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir}
# gene c
#
dest="$1"
self='pyconcurrent'

info="Docs README.rst scripts packaging"
infodir="/usr/share/${self}"

license="Docs/License.rst"
licensedir="/usr/share/licenses/${self}"

# so can make app link in /usr/bin
sitedir=$(/usr/bin/python3 -c "import site; print(site.getsitepackages()[0])")
self_sitedir=${sitedir}/${self//-/_}

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    # shared
    /usr/bin/rsync --mkpath -a ${info} ${dest}${infodir}
    /usr/bin/rsync --mkpath -a ${license} ${dest}/${licensedir}/
    /usr/bin/python -m installer --destdir="$dest" dist/*.whl
    exit 0
fi

